### PR TITLE
Desiree morris

### PR DESCRIPTION
**Pull request by desiquinn**

### CODE REVIEW

**Review by ticotheps — COMMENTED** [review]
How's it coming along, @desiquinn? Were you able to hit MVP last night?

**Comment by desiquinn** [comment]
@ticotheps I actually completed MVP pretty early on yesterday.

**Comment by ticotheps** [comment]
That's awesome, @desiquinn! :) I'm glad you were so punctual, but be careful not to focus **_too_** much on whether you finish the module an hour early or an hour late. We just really want you to hone in on the **_learning_** part of the process, which takes time. Right? 👍

**Comment by ticotheps** [comment]
@desiquinn, in the future, could you please let me know if you've finished the module earlier than expected? I really think you're a great leader and can communicate well. So, any time you finish early, I'd **_love_** to have you open up a zoom call in our slack channel to see if you can assist any of your group-mates that might not be as fast as you in completing the module! I have requested the same from Obaida or anyone else that completes the module early. I also love that in doing so, you'll just be getting more valuable reps for your interview practice! :)

**Pull request merged**
